### ISSUE TITLE
أخطاء كتابية

### ISSUE THREAD

**Issue by osamasado** [RiadKatby/machine-learning-models#2]
- البيانات إذا أردت كشف رسائل التصيد الإلكترونية، **فجمع** عينات من تلك الرسائل. وإذا أردت التنبؤ بأسعار الأسهم في المستقبل، **فبحث** عن سجلات الأسعار السابقة.

- البيانات: إذا أردت كشف رسائل التصيد الإلكترونية، **فاجمع** (قم بجمع) عينات من تلك الرسائل. وإذا أردت التنبؤ بأسعار الأسهم في المستقبل، **فابحث** عن سجلات الأسعار السابقة.

- لذا قررت أن **أ**كتب مقالة **طلما** (طالما) تمنيت

- **يبدو** (يبدأ)محمد - المحلل اللامع - **بإستنباط** (باستنباط)

- أو تكرار **الكلامات** (الكلمات) في نص رسائل التصيد.

**Comment by RiadKatby** [comment]
شكراً اسامة كلهم تم عكسهم
